dataset:
  dataset_size: 100
  max_node_num: 18
  name: ego_18_small
dev: !!python/object/apply:torch.device
- cuda
eval_from: 10
eval_len: 128
exp_dir: exp
exp_name: gridsearch
finalinterval: 1
folder_name: edp-gnn_ego_18_small__Jul-01-16-44-53_15190
hidden: 32
hidden_final: 32
mcmc:
  eps:
  - 1.0
  - 0.5
  - 0.1
  fixed_node_number: true
  grad_step_size:
  - 0.05
  - 0.005
  - 0.0005
  name: langevin
  step_num: 1000
model:
  models:
    model_1:
      channel_num_list:
      - 2
      - 4
      - 8
      - 16
      - 16
      - 8
      - 4
      dropout_p: 0.0
      feature_nums:
      - 16
      - 16
      - 32
      - 64
      - 64
      - 32
      - 16
      gnn_hidden_num_list:
      - 16
      - 16
      - 16
      - 16
      - 16
      - 16
      name: gin
      use_norm_layers: false
  name: edp-gnn
  stack_num: 1
model_save_dir: exp/gridsearch/edp-gnn_ego_18_small__Jul-01-16-44-53_15190/models
noisetype: switched
num_layers: 6
num_levels:
- 32
run_id: '15190'
sample:
  batch_size: 32
save_dir: exp/gridsearch/edp-gnn_ego_18_small__Jul-01-16-44-53_15190
seed: 1234
test:
  batch_size: 32
  split: 0.2
train:
  batch_size: 32
  lr_dacey: 0.999
  lr_init: 0.001
  max_epoch: 5000
  momentum: 0.9
  sample_interval: 1
  save_interval: 1
  shuffle: true
  sigmas:
  - 0.0
  - 0.015625
  - 0.03125
  - 0.046875
  - 0.0625
  - 0.078125
  - 0.09375
  - 0.109375
  - 0.125
  - 0.140625
  - 0.15625
  - 0.171875
  - 0.1875
  - 0.203125
  - 0.21875
  - 0.234375
  - 0.25
  - 0.265625
  - 0.28125
  - 0.296875
  - 0.3125
  - 0.328125
  - 0.34375
  - 0.359375
  - 0.375
  - 0.390625
  - 0.40625
  - 0.421875
  - 0.4375
  - 0.453125
  - 0.46875
  - 0.484375
  - 0.5
  weight_decay: 0.0
weighted_loss: true
