wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1656687156
    t:
      1:
      - 1
      - 55
      3:
      - 16
      4: 3.9.12
      5: 0.12.15
      8:
      - 5
dataset:
  desc: null
  value:
    dataset_size: 200
    in_feature: 1
    max_node_num: 18
    name: ego_18_small
dev:
  desc: null
  value: cuda
dropout:
  desc: null
  value: 1.0e-06
eval_from:
  desc: null
  value: 2
exp_dir:
  desc: null
  value: exp
exp_name:
  desc: null
  value: gridsearch
finalinterval:
  desc: null
  value: 1
folder_name:
  desc: null
  value: ppgn_ego_18_small__Jul-01-16-52-26_249285
hidden:
  desc: null
  value: 32
hidden_final:
  desc: null
  value: 32
linear:
  desc: null
  value: true
mcmc:
  desc: null
  value:
    eps:
    - 0.1
    - 1.0
    fixed_node_number: true
    grad_step_size:
    - 0.05
    - 0.005
    - 0.0005
    name: langevin
    step_num: 1000
model:
  desc: null
  value:
    models:
      model_1:
        channel_num_list:
        - 2
        - 4
        - 4
        - 4
        - 2
        dropout_p: 0.0
        feature_nums:
        - 16
        - 16
        - 16
        - 16
        - 16
        gnn_hidden_num_list:
        - 16
        - 16
        - 16
        - 16
        name: ppgn
        use_norm_layers: false
    name: ppgn
    stack_num: 1
model_save_dir:
  desc: null
  value: exp/gridsearch/ppgn_ego_18_small__Jul-01-16-52-26_249285/models
n_nodes:
  desc: null
  value: 30
noise_mlp:
  desc: null
  value: false
noisetype:
  desc: null
  value: switched
normalization:
  desc: null
  value: instance
num_layers:
  desc: null
  value: 8
num_levels:
  desc: null
  value:
  - 32
run_id:
  desc: null
  value: '249285'
sample:
  desc: null
  value:
    batch_size: 32
samplesize:
  desc: null
  value: 128
save_dir:
  desc: null
  value: exp/gridsearch/ppgn_ego_18_small__Jul-01-16-52-26_249285
seed:
  desc: null
  value: 1234
sigmarandom:
  desc: null
  value: true
test:
  desc: null
  value:
    batch_size: 32
    split: 0.2
train:
  desc: null
  value:
    batch_size: 64
    lr_dacey: 0.999
    lr_init: 0.001
    max_epoch: 5000
    momentum: 0.9
    sample_interval: 1
    save_interval: 1
    shuffle: true
    sigmas: None
    weight_decay: 0.0
weighted:
  desc: null
  value: true
weighted_loss:
  desc: null
  value: true
