wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1665924744
    t:
      1:
      - 1
      - 55
      3:
      - 16
      4: 3.9.12
      5: 0.12.15
      8:
      - 5
dataset:
  desc: null
  value:
    dataset_size: 100
    in_feature: 1
    max_node_num: 20
    name: community_20_small
dev:
  desc: null
  value: cuda
dropout:
  desc: null
  value: 1.0e-06
eval_from:
  desc: null
  value: 1000
exp_dir:
  desc: null
  value: exp
exp_name:
  desc: null
  value: community
finalinterval:
  desc: null
  value: 10
folder_name:
  desc: null
  value: edp-gnn_community_20_small__Oct-16-14-52-20_11953
hidden:
  desc: null
  value: 32
hidden_final:
  desc: null
  value: 32
mcmc:
  desc: null
  value:
    eps:
    - 1.0
    - 0.5
    - 0.1
    fixed_node_number: true
    grad_step_size:
    - 0.05
    - 0.005
    - 0.0005
    name: langevin
    step_num: 1000
model:
  desc: null
  value:
    models:
      model_1:
        channel_num_list:
        - 2
        - 4
        - 8
        - 16
        - 16
        - 8
        - 4
        dropout_p: 0.0
        feature_nums:
        - 16
        - 16
        - 32
        - 64
        - 64
        - 32
        - 16
        gnn_hidden_num_list:
        - 16
        - 16
        - 16
        - 16
        - 16
        - 16
        name: gin
        use_norm_layers: false
    name: ppgn
    stack_num: 1
model_save_dir:
  desc: null
  value: exp/community/edp-gnn_community_20_small__Oct-16-14-52-20_11953/models
n_nodes:
  desc: null
  value: 30
noise_mlp:
  desc: null
  value: false
noisetype:
  desc: null
  value: switched
normalization:
  desc: null
  value: instance
num_layers:
  desc: null
  value: 6
num_levels:
  desc: null
  value:
  - 32
run_id:
  desc: null
  value: '11953'
sample:
  desc: null
  value:
    batch_size: 32
samplesize:
  desc: null
  value: 128
save_dir:
  desc: null
  value: exp/community/edp-gnn_community_20_small__Oct-16-14-52-20_11953
seed:
  desc: null
  value: 1234
test:
  desc: null
  value:
    batch_size: 32
    split: 0.2
train:
  desc: null
  value:
    batch_size: 32
    lr_dacey: 0.999
    lr_init: 0.001
    max_epoch: 5000
    momentum: 0.9
    sample_interval: 1
    save_interval: 1
    shuffle: true
    sigmas:
    - 0.0
    - 0.015625
    - 0.03125
    - 0.046875
    - 0.0625
    - 0.078125
    - 0.09375
    - 0.109375
    - 0.125
    - 0.140625
    - 0.15625
    - 0.171875
    - 0.1875
    - 0.203125
    - 0.21875
    - 0.234375
    - 0.25
    - 0.265625
    - 0.28125
    - 0.296875
    - 0.3125
    - 0.328125
    - 0.34375
    - 0.359375
    - 0.375
    - 0.390625
    - 0.40625
    - 0.421875
    - 0.4375
    - 0.453125
    - 0.46875
    - 0.484375
    - 0.5
    weight_decay: 0.0
weighted_loss:
  desc: null
  value: true
