
# the output files will be stored in the directory <exp_dir>/<exp_name>
exp_dir: exp
exp_name: ego_small

seed: 1235






#instancenorm 16 steps 6x24x24 mlp true
#model_save_dir: 'exp/ego_small/ppgn_ego_small__Apr-05-14-41-30_19768/models'
#second attempt same confg as one above
#model_save_dir: 'exp/ego_small/ppgn_ego_small__Apr-06-12-04-08_18887/models'


#with instance norm noise_mlp_ind 24x24x6
#model_save_dir: 'exp/ego_small/ppgn_ind_ego_small__Apr-06-10-32-06_306/models'

#16 noisemlp_ind_mult instancenorm 6x24x24 ego
#model_save_dir: 'exp/ego_small/ppgn_ind_mult_ego_small__Apr-06-14-41-05_2765/models'

##this is a test for 16 noisemlp_ind instancenorm 6x24x24 ego but with a added norm
#model_save_dir: 'exp/ego_small/ppgn_ind_mult_ego_small__Apr-10-12-43-22_17563/models'
#model_save_dir: 'exp/ego_small/ppgn_ind_mult_ego_small__Apr-10-14-07-20_32672/models'

####this is a test for 16 noisemlp_ind instancenorm 6x24x24 ego but with a added norm and with etter than relu and each individ lin also now activation
#model_save_dir: 'exp/ego_small/ppgn_ind_mult_ego_small__Apr-10-13-38-37_26257/models'

#test1
#model_save_dir: 'exp/ego_small/ppgn_ind_mult_ego_small__Apr-11-09-33-26_3622/models'

#test2
#model_save_dir: 'exp/ego_small/ppgn_ego_small__Apr-11-09-36-22_3337/models'

#model_save_dir: 'exp/ego_small/ppgn_ego_small__Apr-11-15-40-05_31706/models'


##model that was used for 90 test with normal noisemlp and 16 steps 500 eochs
#model_save_dir: 'exp/ego_small/ppgn_ego_small__Apr-12-13-56-26_23169/models'


##100 epochs normalnoisemlp
model_save_dir: 'exp/ego_small/ppgn_ego_small__Apr-12-16-04-54_7243/models'







# uncomment it to save the output files to `save_dir` instead of creating a new directory
#save_dir: 'exp/ego_small/edp-gnn_ego_small_xxx'



dataset:
  dataset_size: 200  # the maximal loaded dataset size
  max_node_num: 18
  name: ego_small  # name of the dataset, the pickle file should be data/<name>.pkl

mcmc:  # hyper parameters in the Langevin MC sampling
  eps:
  - 0.1
  - 1.0
  fixed_node_number: true
  grad_step_size:
  - 0.05
  - 0.005
  - 0.0005
  name: langevin
  step_num: 1000
model:
  name: edp-gnn  # the name of the score-network, should be one of ['gnn', 'mlp', 'cov', 'unet', 'edp-gnn']
  models:
    model_1:
      dropout_p: 0.0
      gnn_hidden_num_list:  # feature number for each EDP-GNN layer
      - 16
      - 16
      - 16
      - 16
      feature_nums:  # F_i
      - 16
      - 16
      - 16
      - 16
      - 16
      channel_num_list:  # C_i
      - 2
      - 4
      - 4
      - 4
      - 2
      name: gin  # the name of the GNN, should be one of ['gin', 'gcn']
      use_norm_layers: false
  stack_num: 1

sample:
  batch_size: 32

test:
  batch_size: 32
  split: 0.2

train:
  batch_size: 32

  lr_dacey: 0.99
  lr_init: 0.001
  momentum: 0.9

  max_epoch: 5001
  sample_interval: 2500  # run sampling after <sample_interval> epochs
  save_interval: 2500 # save the model after <save_interval> epochs

  shuffle: true
  sigmas:
  - 0.0
  - 0.0333
  - 0.0667
  - 0.1
  - 0.1333
  - 0.1667
  - 0.2
  - 0.2333
  - 0.2667
  - 0.3
  - 0.3333
  - 0.3667
  - 0.4
  - 0.4333
  - 0.4667
  - 0.5
  

  weight_decay: 0.0

inter_log:
  log_inter_steps: true
  steps_to_log:
  - 31
  - 30
  - 29
  - 28
  - 27
  - 26
  - 25
  - 24
  - 23
  - 22
  - 21
  - 20
  - 19
  - 18
  - 17
  - 16
  - 15
  - 14
  - 13

